### ISSUE TITLE
(XS) SC-1 Proper Peerplays Connection Support

### ISSUE THREAD

**Issue by MuffinLightning** [peerplays-network/getscatter-walletpack#11]
### **User Story**

Add functionality such that Scatter wallet, when using the Peeprlays plugin, may connect to the peerplays blockchain.
Must use either:
* [ ] existing peerplaysjs-lib websocket connection route (undesirable as expressed by Scatter team)
* [x] using new fetch based approach

### **Impacts**

Describe which portion(s) of Peerplays that may be impacted by your request. Please tick at least one box.

* [X] API (the application programming interface)
* [ ] Build (the build process or something prior to compiled code)
* [ ] Deployment (the deployment process after building such as Docker, Gitlab, etc.)
* [X] Performance (system or user efficiency, etc.)
* [ ] Protocol (the blockchain logic, consensus, validation, etc.)
* [ ] Security (the security of system or user data, etc.)
* [ ] UX (the User Experience)
* [ ] Other (please add below)

### **Additional Context (optional)**

Explore the necessity of the peerplaysjs-lib websocket connectivity method prior to completing the Peerplays Scatter plugin.

## Community / PBSA check list

* [x] Evaluate / Prioritize Feature Request
* [x] Refine User Stories / Requirements
* [ ] Define Test Cases
* [ ] Design / Develop Solution
* [ ] Perform QA/Testing
* [ ] Update Documentation

**Comment by mseaward** [comment]
I am exploring in depth as to whether or not we will require the peerplaysjs-lib websocket connectivity. Thus far, I am inclined to say that it is not necessary. Will update ticket once a conclusion has been made on the details.

**Comment by mseaward** [comment]
#18 after investigation, @MuffinLightning and I are pretty sure that CORS will not be an issue in production mode of the scatter wallet. Thus, we will proceed with a fetch based approach to retrieving data and continue to develop via unit tests as per instruction from Nathan

**Comment by mseaward** [comment]
Closing as this issue initially outlined the instantiation of a websocket connection that once completed, would complete this story. However, we are going to proceed with fetch based calls which means there will be no constant connection to a Peerplays blockchain API node thereby removing the need for this issue.
