### ISSUE TITLE
define functional requirements

### ISSUE THREAD

**Issue by bobinson** [peerplays-network/getscatter-walletpack#4]
Based on the project goals shared here https://github.com/peerplays-network/getscatter-walletpack/wiki/Scatter-Peerplays-Integration-:-Scope we need to gather and finalize the functional requirements of the scatter - peerplays integration project.

The features will also be a subset of the Peerplays wallet.

The functional requirements are here https://peerplays.gitbook.io/community-project-docs/scatter-peerplays-integration/functional-requirements

**Comment by bobinson** [comment]
@MuffinLightning 

1.
> Generate keypair

Is this for an existing peerplays user or for someone to create a new account ?

2. Are we providing support for a user to create a new peerplays account via scatter integration ?  (cc @jonathanbahai  )

**Comment by bobinson** [comment]
3.

> Support for PPY asset

What all can be done with a PPY asset ?  The term support needs to be elaborated.

**Comment by MuffinLightning** [comment]
> @MuffinLightning @belakon1975
> 
> 
> > Generate keypair
> 
> Is this for an existing peerplays user or for someone to create a new account ?
> 
> 1. Are we providing support for a user to create a new peerplays account via scatter integration ?  (cc @jonathanbahai  )

From previous conversations I've had, I believe yes.

> > Support for PPY asset
> 
> What all can be done with a PPY asset ? The term support needs to be elaborated.

Support for PPY Asset in this case just means that the application should be able to recognize the PPY token. More specific features are listed separately.
