### ISSUE TITLE
(XS) Investigate ScatterDesktop

### ISSUE THREAD

**Issue by MuffinLightning** [peerplays-network/getscatter-walletpack#46]
Test application with ScatterDesktop, and identify/troubleshoot any issues.

Investigating to determine what may need to be integrated.

**Comment by mseaward** [comment]
@MuffinLightning still ongoing or can this be closed? This is from the previous milestone and is **late**

**Comment by belakon1975** [comment]
guys, please estimate. I will assume XS for now...
