### ISSUE TITLE
define non functional requirements and accepance

### ISSUE THREAD

**Issue by bobinson** [peerplays-network/getscatter-walletpack#5]
The project needs a well defined non functional criteria. This includes code quality, peer reviews, security audits, license compliance etc.

**Comment by bobinson** [comment]
@MuffinLightning  : please use this https://app.gitbook.com/@peerplays/s/community-project-docs/scatter-peerplays-integration/scatter-wallet-acceptance-criteria-non-functional

**Comment by bobinson** [comment]
@MuffinLightning 

> Operating System support will be the minimum required to run Electron.

Which are the OSes that Scatter and thus we will be supporting needs to be mentioned clearly.

**Comment by MuffinLightning** [comment]
The document should define the OS support
