### ISSUE TITLE
(XXS)  Add PPY icon to the Wallet screen within the Scatter UI.

### ISSUE THREAD

**Issue by mseaward** [peerplays-network/getscatter-walletpack#57]
![Peerplays logomark RGB](https://user-images.githubusercontent.com/36667230/77163447-ddf4e000-6a8c-11ea-9aa6-98fbcad9b32e.png)
Under the GUI uses' wallet section, use the above image instead of a circle with the letter "P" inside it.

**Comment by belakon1975** [comment]
@mseaward  please estimate! I will put XXS for now

**Comment by mseaward** [comment]
Where this logo would be used is in a file host, I think, that we do not have access too. Support for our Logo may be only possible by Scatter team who have access to their hosted resources.
